config/routes.rb
Rails.application.routes.draw do
  resources :users, :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true, optional: true

  validates :street, :city, :zip_code, presence: true

  validates :zip_code, format: { with: /\A\d{2}-\d{3}\z/,
    message: "only polish zip-code allowed" }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

  has_one :address, as: :addressable
  has_many :employees, class_name: "User"
  accepts_nested_attributes_for :address

  validates :name, presence: true, length: { maximum: 200,
    too_long: '%{count} characters is the maximum allowed' }
end

app/models/user.rb
class User < ApplicationRecord
  has_one :address, as: :addressable
  belongs_to :company, optional: true
  accepts_nested_attributes_for :address

  validates :first_name, :last_name, presence: true, length: { maximum: 100,
    too_long: '%{count} characters is the maximum allowed' }
  validates :email, presence: true, format: /\A.+@.+\..+\z/, uniqueness: true
  validates :phone, numericality: true, allow_blank: true
  validate :date_of_birth_cannot_be_in_the_future

  def company_attributes=(company_attributes)
    self.company = Company.find_or_create_by(name: company_attributes[:name])
    if self.company.address.blank?
      self.company.update(company_attributes)
    end
  end

  def date_of_birth_cannot_be_in_the_future
    if date_of_birth.present? && date_of_birth > Date.today
      errors.add(:date_of_birth, "can't be in the future")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /company
  # GET /company.json
  def index
    @companies = Company.includes(:employees)
  end

  # GET /company/1
  # GET /company/1.json
  def show
    @company = Company.includes(:employees).find(params[:id])
  end

  # GET /company/new
  def new
    @company = Company.new
    @address = @company.build_address
  end

  # GET /company/1/edit
  def edit
  end

  # POST /company
  # POST /company.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/1
  # PATCH/PUT /company/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/1
  # DELETE /company/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(
        :name,
        :address_id,
        :user_id,
        :email,
        {address_attributes: [:street, :city, :zip_code, :country, :id] })
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user.build_address
    @company = @user.build_company
    @company.build_address
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.address.addressable = @user
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.'}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :birth_date,
        :phone,
        :company_id,
        :address_attributes => [ :street, :city, :zip_code, :country ] ,
        :company_attributes => [ :name, :address_attributes => [ :street, :city, :zip_code, :country] ] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.slim
= simple_form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      h2 = "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      ul
        - @company.errors.full_messages.each do |message|
          li = message

  .input
    = f.input :name
  ul
    = f.simple_fields_for :address do |address|
      = render :partial => 'shared/address/form', :locals => {:f => address }
  = f.submit :class => "btn btn-success"

app/views/companies/destroy.html.slim
h1 Company#destroy
p Find me in app/views/company/destroy.html.slim

app/views/companies/edit.html.slim
.container
  h1 Edit
  .col-5
    == render 'form'
  .btn-group.d-flex.justify-content-center
    => link_to 'Show', @company, class: "btn btn-dark"
    =< link_to 'Back', companies_path, class: "btn btn-dark"

app/views/companies/index.html.slim
.container-fluid
  h1 List of all companies
  table [class="table"]
    thead [class="thead-dark"]
      tr
        th Company name
        th Country
        th City
        th Employees
        th 
        th 
        th 

    tbody
      - @companies.each do |company|
        tr
          td = company.name
          - unless company.address.blank?
            td = company.address.country
            td = company.address.city
          - else
            td = " "
            td = " "
          td = company.employees.count
          td
            = link_to 'Show', company, class: "btn btn-outline-primary"
          td
            = link_to 'Edit', edit_company_path(company), class: "btn btn-outline-warning"
          td
            = link_to 'Destroy', company, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-outline-danger"

  br
  .btn-group.d-flex.justify-content-center
    = link_to 'New Company', new_company_path, class: "btn btn-dark"

app/views/companies/new.html.slim
.container
  h1 New company
  .col-5
    == render 'form'
  .btn-group.d-flex.justify-content-center
    = link_to 'Back', companies_path, class: "btn btn-dark"

app/views/companies/show.html.slim
.container
  .col-5
  p
    strong Company: 
    = @company.name
  p
    - unless @company.address.blank?
      strong Address: 
      ul
        li 
          strong Street: 
          = @company.address.street
        li 
          strong City: 
          = @company.address.city
        li 
          strong zip-code: 
          = @company.address.zip_code
        li
          strong Country:   
          = @company.address.country

  p
    strong Employees: 
    ul
      - @company.employees.each do |emp|
        li
          p
            = emp.first_name
            = " "
            = emp.last_name
          p 
            = emp.email
          hr
  .btn-group.d-flex.justify-content-center
    => link_to 'Edit', edit_company_path(@company), class: "btn btn-dark"
    =< link_to 'Back', companies_path, class: "btn btn-dark"

app/views/companies/update.html.slim
h1 Company#update
p Find me in app/views/company/update.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChimeraPrime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow p-3 mb-5">
  <a class="navbar-brand" href="#">Chimera Prime</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Users', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Companies', companies_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
  <ul class="nav nav-pills">
    <li class="nav-item btn-group dropleft">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Create
    </button>
    <div class="dropdown-menu">
      <%= link_to 'New User', new_user_path, class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to 'New Company', new_company_path, class: "dropdown-item" %>
    </div>
  </li>
  </ul>
</nav>
    <%= yield %>
  </body>
</html>

app/views/shared/address/_form.html.slim
/ li.field
/   = f.label :street
/   = f.text_field :street
/ li.field
/   = f.label :city
/   = f.text_field :city
/ li.field
/   = f.label :zip_code
/   = f.text_field :zip_code
/ li.field
/   = f.label :country
/   = f.text_field :country
.fields
  = f.input :street
  = f.input :city
  = f.input :zip_code
  = f.input :country

app/views/users/_form.html.slim
= simple_form_for @user, wrapper: :vertical_form do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :date_of_birth, include_blank: true, start_year: Date.today.year - 110, end_year: Date.today.year
  = f.input :phone

  Strong Address 
  ul 
    = f.simple_fields_for :address do |address|
      = render :partial => 'shared/address/form', :locals => {:f => address }
  Strong Company
  ul
    = f.simple_fields_for :company do |company_form| #refactor with custom wrapper
      = company_form.input :name 
      = company_form.simple_fields_for :address do |company_address|
        = company_address.input :street, required: false
        = company_address.input :city, required: false
        = company_address.input :zip_code, required: false
        = company_address.input :country, required: false
  = f.submit class: "btn btn-success"
  

app/views/users/edit.html.slim
.container
  h1 Editing user
  .col-5
    == render 'form'
  .btn-group.d-flex.justify-content-center
    => link_to 'Show', @user, class: "btn btn-dark"
    =< link_to 'Back', users_path, class: "btn btn-dark"

app/views/users/index.html.slim
.container-fluid
  h1 List of users 
  table [class="table"]
    thead [class="thead-dark"]
      tr
        th [scope="col"] First name
        th [scope="col"] Last name
        th [scope="col"] Email
        th [scope="col"] Date of Birth
        th [scope="col"] Phone number
        th [scope="col"] Street
        th [scope="col"] City
        th [scope="col"] Zip Code
        th [scope="col"] Country
        th [scope="col"] Company
        th 
        th
        th
    tbody
      - @users.each do |user|
        tr
          td = user.first_name
          td = user.last_name
          td = user.email
          td = user.date_of_birth
          td = user.phone
          td = user.address.street
          td = user.address.city
          td = user.address.zip_code
          td = user.address.country
          - if !user.company.blank? 
            td = user.company.name
          - else
            td 
          td 
            = link_to 'Show', user, class: "btn btn-outline-primary"
          td 
            = link_to 'Edit', edit_user_path(user), class: "btn btn-outline-warning"
          td
            = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-outline-danger"

  br
  .btn-group.d-flex.justify-content-center
    = link_to 'New User', new_user_path, class: "btn btn-dark"

app/views/users/new.html.slim
.container
  h1 New user
  .col-5
    == render 'form'
  .btn-group.d-flex.justify-content-center
    = link_to 'Back', users_path, class: "btn btn-dark"

app/views/users/show.html.slim
.container
  .col-5
    p
      strong First name: 
      = @user.first_name
    p
      strong Last name: 
      = @user.last_name
    p
      strong Email: 
      = @user.email
    p
      strong Date of birth: 
      = @user.date_of_birth
    p
      strong Phone: 
      = @user.phone
    p
      strong Address: 
      li 
      strong Street: 
      = @user.address.street
      li 
        strong City: 
        = @user.address.city
      li 
        strong zip-code: 
        = @user.address.zip_code
      li
        strong Country:   
        = @user.address.country
    p
      - if !@user.company.blank? 
        strong Company: 
        = @user.company.name
      - else
  .btn-group.d-flex.justify-content-center
    => link_to 'Edit', edit_user_path(@user), class: "btn btn-dark"
    =< link_to 'Back', users_path, class: "btn btn-dark"